### ISSUE TITLE
佬什么时候来个 C++ 版本

### ISSUE THREAD

**Issue by lc6464** [Emon14435/ZHKU-OJ-Record#1]
🤔

**Comment by UzLung1435** [comment]
Java is enough to pass these online judge exam.
________________________________
发件人: LC ***@***.***>
发送时间: 2024年12月14日 22:06
收件人: UzLung1435/ZHKU-OJ-Record ***@***.***>
抄送: Subscribed ***@***.***>
主题: [UzLung1435/ZHKU-OJ-Record] 佬什么时候来个 C++ 版本 (Issue #1)


🤔
